const data = {
    products: [
      {
        _id: '1',
        name: 'Bakery Product One',
        category: 'Shirts',
        image: '/images/blackforest-cake.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Bakery Product Two',
        category: 'Shirts',
        image: '/images/blackforest-cake.jpg',
        price: 100,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Bakery Product Three',
        category: 'Shirts',
        image: '/images/blackforest-cake.jpg',
        price: 220,
        countInStock: 0,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Bakery Product Four',
        category: 'Pants',
        image: '/images/blackforest-cake.jpg',
        price: 78,
        countInStock: 15,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Bakery Product Five',
        category: 'Pants',
        image: '/images/blackforest-cake.jpg',
        price: 65,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Bakery Product Six',
        category: 'Pants',
        image: '/images/blackforest-cake.jpg',
        price: 139,
        countInStock: 12,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;